{% set name = "wasmtime" %}
{% set version = "41.0.0" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/bd/df/0867edd9ec26eb2e5eee7674a55f82c23ec27dd1d38d2d401f0e308eb920/wasmtime-{{ version }}-py3-none-manylinux1_x86_64.whl
  sha256: ad7e866430313eb2ee07c85811e524344884489d00896f3b2246b65553fe322c

build:
  number: 0
  skip: true  # [not linux]
  script: "{{ PYTHON }} -m pip install https://files.pythonhosted.org/packages/bd/df/0867edd9ec26eb2e5eee7674a55f82c23ec27dd1d38d2d401f0e308eb920/wasmtime-41.0.0-py3-none-manylinux1_x86_64.whl --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - typing_extensions

test:
  imports:
    - wasmtime

about:
  home: https://github.com/bytecodealliance/wasmtime-py
  license: Apache-2.0
  summary: "Wasmtime Python bindings (WebAssembly runtime)"

extra:
  recipe-maintainers:
    - alexcrichton
